### ISSUE TITLE
XSS Vulnerability -> Name/Last Name/ID input

### ISSUE THREAD

**Issue by Liadc** [erelsgl/badkan#9]
XSS Vulnerability while inputting name/last name/ID while user registers AND while editting in profile page.

### **Should sanitize all inputs from users.**

added image for specific page.

Thanks, 
Liad Cohen.
(Student in your C++ Course).

<br> 

[image link](https://prnt.sc/mvzqxo)

![image](https://user-images.githubusercontent.com/6436094/54090335-d0861f80-437b-11e9-8042-c68d698076ac.png)

**Comment by Liadc** [comment]
Sanitize input in this page:

![image](https://user-images.githubusercontent.com/6436094/54090411-979a7a80-437c-11e9-959c-9e9e50a92b8b.png)

**Comment by erelsgl** [comment]
Thanks a lot for reporting this. It should be fixed now.
If you find any other issues, you are welcome to report them here:
https://github.com/SamuelBismuth/badkan
this is now the main fork.
